# Map Topic discovery
discovery_rate: 0.5
map_topic: map
map_namespace: multijackal

# Map matching
matching_rate: 0.3
matching_confidence: 0.7

# Map merging
merging_rate: 0.6
publish_merged_map: true
publish_tf: true
merged_map_topic: merged_map
world_frame: map

# Setting own map to world zero position
multijackal_02/init_pose_x: 0.0
multijackal_02/init_pose_y: 0.0
multijackal_02/init_pose_z: 0.0
multijackal_02/init_pose_yaw: 0.0