# Map Topic discovery
discovery_rate: 0.5
map_topic: map
map_namespace: multijackal

# Map matching
matching_rate: 0.2
matching_confidence: 0.7
dilation: 15 # Obstacle dilation (4 - 15 range is generally good)
blur_kernel_size: 9
refine_transforms: true # Computationally heavy
refiner_radius: 2.0 # meters
refiner_resolution: 0.5 # meters

# Map merging
merging_rate: 0.6
publish_merged_map: true
publish_tf: true
merged_map_topic: merged_map
world_frame: map

# Setting own map to world zero position
multijackal_09/init_pose_x: 0.0
multijackal_09/init_pose_y: 0.0
multijackal_09/init_pose_z: 0.0
multijackal_09/init_pose_yaw: 0.0

multijackal_03/static_merge: true

# For testing only. To be removed before demo
#multijackal_01/init_pose_x: 7.349
#multijackal_01/init_pose_y: 10.253
#multijackal_01/init_pose_z: 0.0
#multijackal_01/init_pose_yaw: -0.044
#multijackal_01/static_merge: true
#multijackal_02/init_pose_x: 5.351
#multijackal_02/init_pose_y: 10.539
#multijackal_02/init_pose_z: 0.0
#multijackal_02/init_pose_yaw: -3.115
#multijackal_02/static_merge: true

